blank_issues_enabled: false
contact_links:
  - name: Search the Docs | 搜索文档
    url: https://kookybot.rtfd.io
    about: Refer to the docs and search for what you are looking for. | 参考文档并搜索您所需的内容。
  - name: Search or ask in KOOK Server | 在 KOOK 服务器中搜索或提问
    url: https://kook.top/wnWOP9
    about: Ask questions and discuss with KookyBot maintainers and other KookyBot users in real-time. | 在 KOOK 服务器中搜索或提问，与 KookyBot 的维护者和其他 KookyBot 用户进行实时交流。
