name: Content request
description: Suggest new contents for our documentation
title: "[Content Request]: "
labels: ["enhancement"]
assignees: Cubik65536

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request new contents for KookyBot-Docs!
        
        > ### Important! :warning:
        > 
        > The issue list is reserved exclusively for bug reports and feature requests. If you open an issue that does not conform to the requirements, it will be closed.
        >
        > Please refer to the following resources before opening an issue:
        > * Search the [docs](https://kookybot.rtfd.io)
        > * Search or ask in [KOOK Server](https://kook.top/wnWOP9)

  - type: checkboxes
    id: confirm
    attributes:
      label: "Please choose if applies:"
      options:
      - label: I'm currently working on adding these contents.
        required: false

  - type: input
    id: content-title
    attributes:
      label: Suggest a title for the content.
      description: Give a title to the new content you want to see in our documentation.

  - type: textarea
    id: content-description
    validations:
      required: true
    attributes:
      label: Describe the content you'd like
      description: A clear and concise description of what you want to see in our documentation.

  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: Add any other context, code examples, or references about the content request here.

  - type: markdown
    attributes:
      value: |
        ---------
        
        Before you submit this issue, please confirm the following:
        
        **1. Do these contents or similar ones already appear in the documentation?**
        
        Please search to see if these contents or similar ones already exists.
        
        ---------
  - type: checkboxes
    id: terms
    attributes:
      label: Please accept these terms
      options:
        - label: I have searched the [documentation](https://kookybot.rtfd.io) and no related contents exists before
          required: true

